name: 'Hello World'
description: 'build HMOS libraries'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: cmd
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: cmd
    - run: echo ${{ github.action_path }}
      shell: cmd
    - run: cd ${{ github.action_path }} | dir
      shell: cmd
    - run: ${{ github.action_path }}\goodbye.sh
      shell: cmd
